# LESSON: Docker YAML (Docker Compose)
# Bu dosya, geliştirme ortamımız için gerekli servisleri (şu an için veritabanı)
# kolayca ayağa kaldırmamızı sağlar. 'docker-compose up' komutu yeterlidir.
version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: lesson-postgres
    environment:
      # LESSON: Güvenlik (Secrets)
      # Normalde parolalar burada açık yazılmaz, Docker Secrets veya .env ile yönetilir.
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Lesson_Db
    ports:
      - "5435:5432" # Lokal makinenin 5435 portunu container'ın 5432'sine bağla
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: # Veritabanı kapansa bile datanın kaybolmaması için volume (kalıcı disk)